### ISSUE TITLE
Process exception list

### ISSUE THREAD

**Issue by shivermetimber** [hasherezade/hollows_hunter#10]
There are some truly awful products out the that will fail HH runs (ie Panda) but may need to run anyway. Would like to request an command line option of processes to *not* be scanned by HH.

**Comment by hasherezade** [comment]
Hi! Sure it can be done. 
But I am also curious what exactly are the problem you experienced? Does HH hangs on scanning that processes? Or in what ways they disturb it? Maybe it is an error in HH that I need to fix.

**Comment by shivermetimber** [comment]
Actually, an HH scan on a system with the Panda AV will generate 25 to 50 (valid) alerts per system based on the poor coding practice that that vendor has used. I can send you additional details If you are interested in those. To deal with that problem, we now loop through each process on a box, make sure it is not Panda AV, and then send the individual process to HH. I would like to go back to just running against the box in one command if I could. I also see some other security (EDR) tools that alert on anything that touches lsass so it is tempting to skip that as well.

    On Saturday, June 5, 2021, 09:39:23 AM EDT, hasherezade ***@***.***> wrote:  
 
 


Hi! Sure it can be done.
But I am also curious what exactly are the problem you experienced? Does HH hangs on scanning that processes? Or in what ways they disturb it? Maybe it is an error in HH that I need to fix.

**Comment by hasherezade** [comment]
ok, I see. I will implement the exclusion list soon. like there is the [`/mignore` parameter](https://github.com/hasherezade/pe-sieve/wiki/4.6.-Ignore-modules-(mignore)) which ignores specific DLLs, I will make a `/pignore` to ignore processes by names.

**Comment by shivermetimber** [comment]
That would be awesome -  Thank you!

    On Saturday, June 5, 2021, 12:40:33 PM EDT, hasherezade ***@***.***> wrote:  
 
 


ok, I see. I will implement the exclusion list soon. like there is the /mignore parameter which ignores specific DLLs, I will make a /pignore to ignore processes by names.

**Comment by hasherezade** [comment]
I added the feature, please check it and let me know what do you think. You can download the latest build from AppVeyor (more info [here](https://github.com/hasherezade/hollows_hunter/wiki#download))

**Comment by shivermetimber** [comment]
I will get on it immediately. Thanks!


    On Monday, June 7, 2021, 06:40:27 PM EDT, hasherezade ***@***.***> wrote:  
 
 


I added the feature, please check it and let me know what do you think. You can download the latest build from AppVeyor (more info here)

**Comment by shivermetimber** [comment]
We ran it through a number of tests and it looks solid!

    On Monday, June 7, 2021, 06:40:27 PM EDT, hasherezade ***@***.***> wrote:  
 
 


I added the feature, please check it and let me know what do you think. You can download the latest build from AppVeyor (more info here)

**Comment by hasherezade** [comment]
Cool, feel free to close the issue once you finish testing.
