### ISSUE TITLE
Hollows hunter question - static signature support

### ISSUE THREAD

**Issue by harryeetsource** [hasherezade/hollows_hunter#14]
Hello again hasherezade, I was wondering if HollowsHunter uses any static signature detection, or if HollowsHunter uses prebuilt yara rules or any methods that would generate plaintext malware strings in memory. Thank you much! Have a great day!

**Comment by hasherezade** [comment]
hi, currently it doesn't support any configurable signatures, but I am planning to support them at some point in the future. but rather not a full Yara scan, because that would be too slow. just very simple binary signatures.

**Comment by harryeetsource** [comment]
Hello! Thank you very much for the reply, I am in a cyber-engagement, and wanted to rule out any potential false positives.  I appreciate your work. No rush on static signature support.
