### ISSUE TITLE
Dumping PE with malformed header

### ISSUE THREAD

**Issue by thatskriptkid** [hasherezade/hollows_hunter#18]
Hi! In the picture below, on the left side, there is a PE in memory with malformed header. On the right side, there is a corresponding  dump that was made by hollows_hunter. Is it an intentional behavior of a tool to reconstruct header when dumping? Especialy changing RR to MZ and SS to PE.

![image_20231226174918](https://github.com/hasherezade/hollows_hunter/assets/8300184/4e9f769c-68ac-469c-b8cb-6708aaa67150)

**Comment by hasherezade** [comment]
hi @thatskriptkid !
Yes, sure, the header reconstruction is intentional. Do you have any problem with it?

**Comment by thatskriptkid** [comment]
> hi @thatskriptkid ! Yes, sure, the header reconstruction is intentional. Do you have any problem with it?

No problem, I was just curious, thanks for the answer
