### ISSUE TITLE
Compiling issue using Cmake

### ISSUE THREAD

**Issue by moosa-aslam** [hasherezade/hollows_hunter#4]
Unable to compile Hollow's hunter.

![123](https://user-images.githubusercontent.com/39161743/64012605-78b0c000-cb37-11e9-9fa4-73fe1ec58eed.png)

**Comment by hasherezade** [comment]
The CMake files are fine (also AppVeyor uses them and builds the project without any problems: https://ci.appveyor.com/project/hasherezade/hollows-hunter/build/job/f9s45l81glo93jdi). There is some mistake on your side.

First of all, I can see that you downloaded just a master, which is not the complete source. You should have clone it along with the submodules.

Please follow this small guide:
1. clone the full repository recursively (you must have git installed):
```
git clone --recursive https://github.com/hasherezade/hollows_hunter.git
```
![clone](https://user-images.githubusercontent.com/3115348/64069688-fe735f00-cc4e-11e9-8730-b14b9c9e5d0f.png)

2. As a result you should have the following directory with the complete sources:

![sources_dir](https://user-images.githubusercontent.com/3115348/64069711-7f325b00-cc4f-11e9-9ac5-6687f4919456.png)

In the complete sources, the directory `pe-sieve` have is not empty.

3. Once you have the complete sources cloned, you must point the root directory of the source to CMake. 

![select_dir](https://user-images.githubusercontent.com/3115348/64069724-ebad5a00-cc4f-11e9-8275-d5d98299a061.png)

4. Click configure, and choose a proper build environment. I recommend Visual Studio. There are many options, <B>but you MUST make sure that you choose the option that you have installed on your machine</B>.
![choose_vs](https://user-images.githubusercontent.com/3115348/64069734-3dee7b00-cc50-11e9-8fd6-3f302298339c.png)
When I choose Visual Studio 2015, which is not installed on my machine, I get exactly the same error.
![invalid](https://user-images.githubusercontent.com/3115348/64069737-64acb180-cc50-11e9-90d5-3f0ea48f4896.png)

Once you chosen the wrong thing, you must first delete the cache to be able to correct your mistake.
```
File -> Delete Cache
```
Once you will have the correct environment set, I ensure you that it will work.

**Comment by moosa-aslam** [comment]
Followed your guide 

1) Configured and generated project.
![Compiler PIN-2019-09-02-09-34-19](https://user-images.githubusercontent.com/39161743/64090893-f870a180-cd66-11e9-9ef4-699d861c45fd.png)

2) Project folder looks like this
![Compiler PIN-2019-09-02-09-35-05](https://user-images.githubusercontent.com/39161743/64090903-0292a000-cd67-11e9-88d5-cf3965798471.png)

3) Project Errors
![Compiler PIN-2019-09-02-09-47-40](https://user-images.githubusercontent.com/39161743/64090908-0a524480-cd67-11e9-8ecf-ef916ccb34fb.png)

**Comment by hasherezade** [comment]
ok, so the first problem is resolved and project got generated.

With the second thing - you seem to be having outdated version of the Windows SDK, where the definitions of delay load imports are missing... I saw such case before, and there are some workarounds. But I need to be sure.
What exactly is your OS and the visual Studio version? Can you possibly switch to the newer?

**Comment by moosa-aslam** [comment]
> ok, so the first problem is resolved and project got generated.
> 
> With the second thing - you seem to be having outdated version of the Windows SDK, where the definitions of delay load imports are missing... I saw such case before, and there are some workarounds. But I need to be sure.
> What exactly is your OS and the visual Studio version? Can you possibly switch to the newer?

Windows 7 64 Bit
Visual Studio 2010 

yes I can visual studio 2012 should do the work >

**Comment by hasherezade** [comment]
You can try, but it may not be enough.
You may also try to install [Visual Studio 2017 or above](https://visualstudio.microsoft.com/vs/?rr=https%3A%2F%2Fwww.google.com%2F) on Windows 10 downloaded from [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

**Comment by moosa-aslam** [comment]
After compiling on Visual Studio 2012 
![Compiler PIN-2019-09-02-17-05-12](https://user-images.githubusercontent.com/39161743/64144146-ad20c680-ce2c-11e9-9764-4d53572f896c.png)

**Comment by hasherezade** [comment]
As far as I can see, it is the same issue as before, with missing definition of delayload imports.
Can you try with the second solution that I proposed?

**Comment by hasherezade** [comment]
I made adjustments to support the old SDKs.
Try to update the project along with its submodules:
```
git pull --recurse-submodules
git submodule update --remote --recursive
```
or, delete the project and download it again:
```
git clone --recursive https://github.com/hasherezade/hollows_hunter.git
```
and repeat all the steps that I mentioned in the small guide.
Let me know if it helped.
