### ISSUE TITLE
Can we have a summary of the detected items?

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [hasherezade/hollows_hunter#7]
If I got it right, Hollows Hunter identifies different kinds of potentially dangerous stuff:

* hooks
* patches
* implants
* shell code

I'd like to be able to quickly compare scan results against past scan results and see whether an application has still the same dangeous stuff as before or it has new "features".

My proposal would be to name the dangerous stuff in the summary, Maybe like so:

```
SUMMARY:
Scan at: 06/18/20 07:43:09 (1592458989)
Finished scan in: 81782 milliseconds
[+] Total Suspicious: 15
[+] List of suspicious:
[ 0]: PID: 3164, Name: HsMgr.exe [detected: H, P, I, S]
[ 1]: PID: 9176, Name: HsMgr64.exe [detected: H, P, I, S]
[ 2]: PID: 1936, Name: steam.exe [detected: H]
...
```

**Comment by hasherezade** [comment]
HI! I see that it is your first experience with HollowsHunter. Take your time to get familiar with the tool and parameters - HollowsHunter wiki is very brief, and contains only those that are not self explanatory. Check also [PE-sieve wiki](https://github.com/hasherezade/pe-sieve/wiki) that contains a lot of important stuff.

You will see that what you are proposing is already implemented - just use `/json` parameter - and the JSON summary will be printed on stdout. What is shown in the basic summary is just a list of names, but extened summary is also available in more human-readable form.

![json_vs_summary](https://user-images.githubusercontent.com/3115348/85003162-24bea880-b156-11ea-993f-67cc321637be.png)

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
Thanks for the explanation and patience.
